version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    command: ["npm", "run", "dev"] # Ensure the backend runs the dev script

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_API_URL=http://backend:3001 # Set environment variable to connect to the backend
    command: ["npm", "run", "dev"] # Ensure the frontend runs the dev script

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
